name: ClockBlocker
main: com.andoutay.clockblocker.ClockBlocker
version: 0.9.0

description: >
             Monitors redstone activity and interrupts any circuits that are repeating too quickly.

commands:
    clockblocker:
        description: Starts or stops monitoring of redstone activity on the server
        usage: 'usage: /<command> <start|stop|view|tp>. Use /<command> help for help'
        aliases: cb

permissions:
    clockblocker.*:
        description: Gives access to all ClockBlocker functionality
        default: false
        children:
            clockblocker.start: true
            clockblocker.stop: true
            clockblocker.view: true
            clockblocker.tp: true
            clockblocker.reload: true
            clockblocker.version: true
    clockblocker.start:
        description: Allows the player to start monitoring
        default: false
    clockblocker.stop:
        description: Allows the player to stop monitoring
        default: false
    clockblocker.view:
        description: Allows the player to view suspicious redstone activity
        default: false
    clockblocker.tp:
        description: Allows the player to teleport to suspicious activity
        default: false
    clockblocker.reload:
        description: Allows the player to reload the config file
        default: false
    clockblocker.version:
        description: Allows the player to check the plugin version
        default: false
    